### ISSUE TITLE
Update Prisma Schema - Cascade Delete

### ISSUE THREAD

**Issue by Anclagen** [NoroffFEU/agency-api.noroff.dev#112]
We need to setup cascading delete on the prisma schema

- [ ] Deleting a user deletes all related applications and offers.
- [ ] Deleting a listing deletes all related applications and offers.
- [ ] Deleting a application deletes all related offers.
- [ ] Deleting a company, removes all existing Admins, then deletes all related listings, applications and offers. 

Other future considerations could be that emails about deleted companies, applications, offers and listings are sent

**Comment by Jarle302** [comment]
Issue Resolution and QA Pending: I've implemented changes aimed at resolving the issue, which is now awaiting QA confirmation.

Cascading Delete Impact: It's important to note that with our current cascading delete setup, deleting a company will result in the removal of all associated users, extending beyond just the admins.


Potential issue with Current Setup: Our current approach might not align with the intended functionality if the goal is to only delete admin users.
Suggested Modification: Consider removing the onDelete cascade from the company-user relationship. We can then handle admin deletions through specific logic outside of Prisma.


Further Investigation: My current understanding of the project's broader aspects is limited, which may affect the decision on this modification.
I suggest opening two issues:
Investigation Issue: To explore whether this adjustment aligns with our project goals.
Implementation Issue: To develop and integrate the logic for admin-only deletion if deemed necessary.
Any insights or suggestions are welcome, especially regarding the potential need for these changes.
